### ISSUE TITLE
l2chroot cannot be downloaded because cyberciti.biz requires cookies and javascript

### ISSUE THREAD

**Issue by boris-hocde** [geerlingguy/ansible-role-ssh-chroot-jail#31]
The file stored in `/usr/local/bin/l2chroot` contains an HTML error page instead of the actual script. Like if cyberciti.biz is behind a WAF blocking automated downloads. The mentioned errors are:

* This website is using a security service to protect itself from online attacks. The service requires full cookie support in order to view the website. Please enable cookies on your browser and try again.
* This website is using a security service to protect itself from online attacks. The service requires full JavaScript support in order to view the website. Please enable JavaScript on your browser and try again.
* This website is using a security service to protect itself from online attacks. You performed an action that triggered the service and blocked your request.

To reproduce:

```
curl https://www.cyberciti.biz/files/lighttpd/l2chroot.txt
```

This is causing your role to fail later, during the `add binary libs via l2chroot` handler, with errors "[Errno 8] Exec format error".

To mitigate the issue, I changed `ssh_chroot_l2chroot_url` to https://gist.githubusercontent.com/andypowe11/60f4d8b38a164a2547174a6d62393bba/raw/b97e600684105105588430b24ee9ced9298deb7d/l2chroot (and deleted the stored HTML page).

Thank you for your amazing work ❤️

**Comment by geerlingguy** [comment]
I opened a PR that incorporates the script into the role itself, since it's a simple thing and CI is breaking now because of the download issue; it keeps the references and header to the cyberciti URL though.

**Comment by geerlingguy** [comment]
Fixed via above PR.
